name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pnpm
      run: |
        npm install -g pnpm
        # Adding the npm bin directory to the PATH
        echo "::add-path::$(npm bin -g)"
    
    - name: Verify pnpm installation
      run: pnpm --version

    - name: Install dependencies
      run: |
        pnpm install
        pnpm add argon2 drizzle-orm pg pino pino-pretty zennv zod jsonwebtoken fastify-zod fastify-guard fastify
        pnpm add zod-to-json-schema @types/jsonwebtoken typescript tsx drizzle-kit @types/pg -D

    - name: Initialize TypeScript
      run: npx tsc --init

    - name: Build project
      run: pnpm build

    - name: Run tests
      run: pnpm test
